-- AlterEnum
ALTER TYPE "ResourceType" ADD VALUE IF NOT EXISTS 'MO';
ALTER TYPE "AssigneeRole" ADD VALUE IF NOT EXISTS 'MO';
ALTER TYPE "JiraSubtaskRole" ADD VALUE IF NOT EXISTS 'mo';

-- AlterTable
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "moHours" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "moStartDate" DATE;
