ALTER TABLE "Task" ADD COLUMN "carriedFromPreviousSprint" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN "remainingFeHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingBeHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingAndroidHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingIosHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingQcHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingIntegrationHours" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN "remainingBufferHours" DOUBLE PRECISION;
